documentation_sources:
  - name: "Platform Core"
    repository: "https://gitlab.adimeo.tech/framework/interne/platform-core"
    docs_path: "Resources/docs/"
    branch: "1.0"
    version: "1.2"
  - name: "Platform Grid"
    repository: "https://gitlab.adimeo.tech/framework/interne/platform-grid"
    docs_path: "Resources/docs/"
    branch: "1.0"
    version: "1.2"
  - name: "Platform User"
    repository: "https://gitlab.adimeo.tech/framework/interne/platform-user"
    docs_path: "Resources/doc/"
    branch: "1.0"
    version: "1.2"
